name: Java CI

on:
  push:
    branches:
      - Thanrak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Compile Java
      run: |
        cd Thanrak/HolidayTravelVehicles
        javac Main.java

    - name: Run Main Class
      run: |
        cd Thanrak/HolidayTravelVehicles
        java Main
